AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  AddPartition:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: AddPartition/index.handler
      Runtime: nodejs8.10
      Description: ''
      MemorySize: 128
      Timeout: 15
  DataChangeHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: DataChangeHandler/index.handler
      Runtime: nodejs8.10
      Description: ''
      MemorySize: 128
      Timeout: 15
