AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  AddPartition:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: AddPartition/index.handler
      Runtime: nodejs8.10
      Description: ''
      MemorySize: 128
      Timeout: 15
  DataChangeHandler:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: DataChangeHandler/index.handler
      Runtime: nodejs8.10
      Description: ''
      MemorySize: 128
      Timeout: 15
  Deliverystream:
    Type: 'AWS::KinesisFirehose::DeliveryStream'
    Properties:
      Policies:
        - PolicyName: DeliverToBucketPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 's3:*'
                Resource:
                  - 'Fn::Sub': 'arn:aws:s3:::${s3DataBucket}'
                  - 'Fn::Sub': 'arn:aws:s3:::${s3DataBucket}*'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId':
                  Ref: 'AWS::AccountId'
      ExtendedS3DestinationConfiguration:
        BucketARN:
          'Fn::Join':
            - ''
            - - 'arn:aws:s3:::'
              - Ref: s3DataBucket
        BufferingHints:
          IntervalInSeconds: '60'
          SizeInMBs: '50'
        CompressionFormat: GZIP
        Prefix: /
        RoleARN:
          'Fn::GetAtt':
            - deliveryRole
            - Arn